version: "3.8"

services:
  api:
    image: mihaiconstantin98/docker-swarm-demo:movies-api
    environment:
      PGUSER: admin
      PGPASSWORD: admin
      PGDATABASE: movies
      PGHOST: db
      PGPORT: 5432
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 50M
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 2
    ports:
      - "5555:80"
    networks:
      - db-network
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: movies
    volumes:
      - db-persistent-volume:/var/lib/postgresql/data
      - "${PWD}/database/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql"
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    networks: 
      - db-network
      - db-adminer-network
    
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - db-adminer-network
    depends_on:
      - db

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - 8081:8080
    deploy:
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  db-persistent-volume:

networks:
  db-network:
  db-adminer-network:
